# Generated by Django 5.2 on 2025-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='raiting',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
